//  Course create Constants

export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_ERR = "COURSE_CREATE_ERR ";


//  Course find Constants

export const COURSE_FIND_REQUEST = "COURSE_FIND_REQUEST";
export const COURSE_FIND_SUCCESS = "COURSE_FIND_SUCCESS";
export const COURSE_FIND_ERR = "COURSE_FIND_ERR ";


//  Course findOne Constants

export const COURSE_FINDONE_REQUEST = "COURSE_FINDONE_REQUEST";
export const COURSE_FINDONE_SUCCESS = "COURSE_FINDONE_SUCCESS";
export const COURSE_FINDONE_ERR = "COURSE_FINDONE_ERR ";


//  Course Update Constants

export const COURSE_UPDATE_REQUEST = "COURSE_UPDATE_REQUEST";
export const COURSE_UPDATE_SUCCESS = "COURSE_UPDATE_SUCCESS";
export const COURSE_UPDATE_ERR = "COURSE_UPDATE_ERR ";


//  CourseLesson Create Constants

export const COURSE_LESSON_CREATE_REQUEST = "COURSE_LESSON_CREATE_REQUEST";
export const COURSE_LESSON_CREATE_SUCCESS = "COURSE_LESSON_CREATE_SUCCESS";
export const COURSE_LESSON_CREATE_ERR = "COURSE_LESSON_CREATE_ERR ";


//  CourseChapter Create Constants

export const COURSE_CHAPTER_CREATE_REQUEST = "COURSE_CHAPTER_CREATE_REQUEST";
export const COURSE_CHAPTER_CREATE_SUCCESS = "COURSE_CHAPTER_CREATE_SUCCESS";
export const COURSE_CHAPTER_CREATE_ERR = "COURSE_CHAPTER_CREATE_ERR ";