
//  ReferralLevel Create Constants

export const REFERRAL_LEVEL_CREATE_REQUEST = "REFERRAL_LEVEL_CREATE_REQUEST";
export const REFERRAL_LEVEL_CREATE_SUCCESS = "REFERRAL_LEVEL_CREATE_SUCCESS";
export const REFERRAL_LEVEL_CREATE_ERR = "REFERRAL_LEVEL_CREATE_ERR";


//  ReferralLevel Find Constants

export const REFERRAL_LEVEL_FIND_REQUEST = "REFERRAL_LEVEL_FIND_REQUEST";
export const REFERRAL_LEVEL_FIND_SUCCESS = "REFERRAL_LEVEL_FIND_SUCCESS";
export const REFERRAL_LEVEL_FIND_ERR = "REFERRAL_LEVEL_FIND_ERR";